import Head from 'next/head';

export default function index() {
  return (
    <div>
      <Head>
        <title>About us </title>
        <meta name='description' content='Generated by create next app' />
      </Head>
    </div>
  );
}
