import Head from 'next/head';
import styles from '../styles/Home.module.css';

// Components
import ShortenURL from '../components/ShortenURL/ShortenURL.jsx';
import HeroSection from '../components/HeroSection/HeroSection.jsx';
import Features from '../components/Features/Features.jsx';
import ShortenList from '../components/ShortenList/ShortenList.jsx';
import CTA from '../components/CTA/CTA.jsx';

export default function Home() {
  return (
    <main>
      <Head>
        <title>Eutashort</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HeroSection />
      <ShortenURL />
      <ShortenList />
      <Features />
      <CTA />
    </main>
  );
}
