import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

// Components
import BtnToggleMenu from '../components/Layout/Header/BtnToggleMenu/BtnToggleMenu';
import Logo from '../components/Layout/Header/Logo/Logo';
import AuthLinks from '../components/Layout/Header/AuthLinks/AuthLinks';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossorigin />
        <link
          href='https://fonts.googleapis.com/css2?family=Poppins:wght@500;700&display=swap'
          rel='stylesheet'
        />
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className={styles.hero}>
        <AuthLinks></AuthLinks>
      </section>
    </div>
  );
}
