import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

// Components
import BtnToggleMenu from '../components/Layout/Header/BtnToggleMenu/BtnToggleMenu';
import Logo from '../components/Layout/Header/Logo/Logo';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className={styles.hero}>
        <Logo></Logo>
      </section>
    </div>
  );
}
